version: "2"

services:
  caliper_2.1:
    container_name: caliper_2.1
    image: hyperledger/caliper:0.3.1
    command: launch master --caliper-fabric-gateway-usegateway --caliper-flow-only-test --caliper-fabric-gateway-discovery
    environment:
      - CALIPER_BIND_SUT=fabric:2.1.0
      - CALIPER_BENCHCONFIG=benchmarks/attempt01/config.yaml
      - CALIPER_NETWORKCONFIG=networks/network-config.yaml
    volumes:
      - ./caliper-benchmarks:/hyperledger/caliper/workspace
    network_mode: host
